"use client";
export default function AgentContent() {
    return (
      <div className="space-y-5">
  
        <img
          src="/TPAgentProject.png"
          className="rounded-xl border"
          alt="Agent homepage"
        />
        {/* TITLE */}
        <div>
          <div className = "flex flex-row space-x-5">
          <h2 className="text-3xl font-bold font-montserrat">
            AI Travel Agent
          </h2>
          <a
            href="https://github.com/ksheth24/cf_ai_trip_agent"
            target="_blank"
            rel="noopener noreferrer"
          > 
            <img
              src = "/GitHub.png"
              className = "w-10 "
              alt = "githublogo"
            />
          </a>
          </div>
          <p className="mt-3 text-gray-600">
          An intelligent travel planning agent that creates personalized itineraries, emails trip plans to users, and marks destinations and routes on Google Maps. Streamlines trip planning from generation to real-world navigation.
          </p>
        </div>
        {/* TECH STACK */}
        <div className="flex flex-wrap gap-2">
          {[
            "React",
            "TypeScript",
            "Node.js",
            "Agentic AI",
            "OpenAI API",
            "Agent Tooling",
          ].map((tech) => (
            <span
              key={tech}
              className="rounded-full bg-gray-100 px-3 py-1 text-sm"
            >
              {tech}
            </span>
          ))}
        </div>
        {/* FEATURES */}
        <div>
          <h3 className="mb-3 text-xl font-semibold font-poppins">Key Features</h3>
          <ul className="list-disc list-inside space-y-2 text-gray-700">
            <li>Interactive chat interface with AI </li>
            <li>Dark/Light theme support</li>
            <li>Real-time streaming responses</li>
            <li>State management and chat history</li>
            <li>Modern, responsive UI</li>
            <li>Trip planning capability that allows the AI Agent to plan a trip based off of user provided info</li>
            <li>Email functionality that emails itinerary to you and your travel buddies</li>
            <li>Google maps connection that provides you with Google Maps links to all activities/restaurants</li>
          </ul>
        </div>

        <div>
          <h3 className="mb-3 text-xl font-semibold font-poppins">Custom Tools Created</h3>
          <ul className="list-decimal list-inside space-y-2 text-gray-700">
            <p className="font-bold">The following are all custom-made TypeScript tools to interface with the OpenAI LLM</p>
            <li> PlanTrip: This tool leverages the OpenAI API to create a custom tailored trip itinerary for your desired trip. After providing this tool with a start date, end date, travel destination, and personal interests, the tool feeds this information into OpenAI LLM model to create a travel itinerary. The tool is designed so that the model will always output the itinerary in a way that separates the activities for each day and provides restaurant and recommendations for each day.</li>
            <li>sendEmail: This tool leverages SendGrid API to send the created travel itinerary to travel buddies. After the user provides the emails of whoever needs to receive the email, the agent will parse through this data and make respective API calls. All emails are sent from keshavsheth11@gmail.com</li>
            <li>generateMapLinks: This tool strategically parses through the itinerary generated by the LLM and isolates all activities/restaurants that were planned. Then, this information is passed into Google Maps and a unique Google Maps link is generated for each activity/restaurant.</li>
          </ul>
        </div>

        
      </div>
    );
  }
  